// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: chitchat/grpc/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastType int32

const (
	BroadcastType_BROADCAST_MESSAGE BroadcastType = 0
	BroadcastType_BROADCAST_JOIN    BroadcastType = 1
	BroadcastType_BROADCAST_LEAVE   BroadcastType = 2
)

// Enum value maps for BroadcastType.
var (
	BroadcastType_name = map[int32]string{
		0: "BROADCAST_MESSAGE",
		1: "BROADCAST_JOIN",
		2: "BROADCAST_LEAVE",
	}
	BroadcastType_value = map[string]int32{
		"BROADCAST_MESSAGE": 0,
		"BROADCAST_JOIN":    1,
		"BROADCAST_LEAVE":   2,
	}
)

func (x BroadcastType) Enum() *BroadcastType {
	p := new(BroadcastType)
	*p = x
	return p
}

func (x BroadcastType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BroadcastType) Descriptor() protoreflect.EnumDescriptor {
	return file_chitchat_grpc_proto_proto_enumTypes[0].Descriptor()
}

func (BroadcastType) Type() protoreflect.EnumType {
	return &file_chitchat_grpc_proto_proto_enumTypes[0]
}

func (x BroadcastType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BroadcastType.Descriptor instead.
func (BroadcastType) EnumDescriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_proto_rawDescGZIP(), []int{0}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ClientMessage_Join
	//	*ClientMessage_Chat
	//	*ClientMessage_Leave
	Kind          isClientMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_chitchat_grpc_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetKind() isClientMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ClientMessage) GetJoin() *Join {
	if x != nil {
		if x, ok := x.Kind.(*ClientMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientMessage) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Kind.(*ClientMessage_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *ClientMessage) GetLeave() *Leave {
	if x != nil {
		if x, ok := x.Kind.(*ClientMessage_Leave); ok {
			return x.Leave
		}
	}
	return nil
}

type isClientMessage_Kind interface {
	isClientMessage_Kind()
}

type ClientMessage_Join struct {
	Join *Join `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientMessage_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type ClientMessage_Leave struct {
	Leave *Leave `protobuf:"bytes,3,opt,name=leave,proto3,oneof"`
}

func (*ClientMessage_Join) isClientMessage_Kind() {}

func (*ClientMessage_Chat) isClientMessage_Kind() {}

func (*ClientMessage_Leave) isClientMessage_Kind() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ServerMessage_Broadcast
	//	*ServerMessage_Ack
	//	*ServerMessage_Error
	Kind          isServerMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_chitchat_grpc_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetKind() isServerMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ServerMessage) GetBroadcast() *Broadcast {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Broadcast); ok {
			return x.Broadcast
		}
	}
	return nil
}

func (x *ServerMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Kind.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Kind interface {
	isServerMessage_Kind()
}

type ServerMessage_Broadcast struct {
	Broadcast *Broadcast `protobuf:"bytes,1,opt,name=broadcast,proto3,oneof"`
}

type ServerMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_Broadcast) isServerMessage_Kind() {}

func (*ServerMessage_Ack) isServerMessage_Kind() {}

func (*ServerMessage_Error) isServerMessage_Kind() {}

type Join struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_chitchat_grpc_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Join) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Join) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UTF-8 text, max 128 characters (enforce/validate on server or with protoc-gen-validate)
	Text          string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Sender        string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	LogicalTime   int64  `protobuf:"varint,3,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"` // Lamport/sequence time if used by protocol
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chitchat_grpc_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type Leave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,2,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leave) Reset() {
	*x = Leave{}
	mi := &file_chitchat_grpc_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leave) ProtoMessage() {}

func (x *Leave) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leave.ProtoReflect.Descriptor instead.
func (*Leave) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Leave) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Leave) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type Broadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          BroadcastType          `protobuf:"varint,1,opt,name=type,proto3,enum=chitchat.v1.BroadcastType" json:"type,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	LogicalTime   int64                  `protobuf:"varint,4,opt,name=logical_time,json=logicalTime,proto3" json:"logical_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	mi := &file_chitchat_grpc_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_proto_rawDescGZIP(), []int{5}
}

func (x *Broadcast) GetType() BroadcastType {
	if x != nil {
		return x.Type
	}
	return BroadcastType_BROADCAST_MESSAGE
}

func (x *Broadcast) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Broadcast) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Broadcast) GetLogicalTime() int64 {
	if x != nil {
		return x.LogicalTime
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // numeric error code (consider google.rpc.Status for richer errors)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // human-readable error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_chitchat_grpc_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          string                 `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"` // optional info (e.g. "joined", "ok")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_chitchat_grpc_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_chitchat_grpc_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_chitchat_grpc_proto_proto_rawDescGZIP(), []int{7}
}

func (x *Ack) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_chitchat_grpc_proto_proto protoreflect.FileDescriptor

const file_chitchat_grpc_proto_proto_rawDesc = "" +
	"\n" +
	"\x19chitchat/grpc/proto.proto\x12\vchitchat.v1\"\x9c\x01\n" +
	"\rClientMessage\x12'\n" +
	"\x04join\x18\x01 \x01(\v2\x11.chitchat.v1.JoinH\x00R\x04join\x12.\n" +
	"\x04chat\x18\x02 \x01(\v2\x18.chitchat.v1.ChatMessageH\x00R\x04chat\x12*\n" +
	"\x05leave\x18\x03 \x01(\v2\x12.chitchat.v1.LeaveH\x00R\x05leaveB\x06\n" +
	"\x04kind\"\xa1\x01\n" +
	"\rServerMessage\x126\n" +
	"\tbroadcast\x18\x01 \x01(\v2\x16.chitchat.v1.BroadcastH\x00R\tbroadcast\x12$\n" +
	"\x03ack\x18\x02 \x01(\v2\x10.chitchat.v1.AckH\x00R\x03ack\x12*\n" +
	"\x05error\x18\x03 \x01(\v2\x12.chitchat.v1.ErrorH\x00R\x05errorB\x06\n" +
	"\x04kind\"=\n" +
	"\x04Join\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x03R\vlogicalTime\"\\\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12!\n" +
	"\flogical_time\x18\x03 \x01(\x03R\vlogicalTime\">\n" +
	"\x05Leave\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\flogical_time\x18\x02 \x01(\x03R\vlogicalTime\"\x8a\x01\n" +
	"\tBroadcast\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.chitchat.v1.BroadcastTypeR\x04type\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12!\n" +
	"\flogical_time\x18\x04 \x01(\x03R\vlogicalTime\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x19\n" +
	"\x03Ack\x12\x12\n" +
	"\x04info\x18\x01 \x01(\tR\x04info*O\n" +
	"\rBroadcastType\x12\x15\n" +
	"\x11BROADCAST_MESSAGE\x10\x00\x12\x12\n" +
	"\x0eBROADCAST_JOIN\x10\x01\x12\x13\n" +
	"\x0fBROADCAST_LEAVE\x10\x022N\n" +
	"\bChitChat\x12B\n" +
	"\x04Chat\x12\x1a.chitchat.v1.ClientMessage\x1a\x1a.chitchat.v1.ServerMessage(\x010\x01B&Z$tacoterror/chitchat/grpc/proto;protob\x06proto3"

var (
	file_chitchat_grpc_proto_proto_rawDescOnce sync.Once
	file_chitchat_grpc_proto_proto_rawDescData []byte
)

func file_chitchat_grpc_proto_proto_rawDescGZIP() []byte {
	file_chitchat_grpc_proto_proto_rawDescOnce.Do(func() {
		file_chitchat_grpc_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chitchat_grpc_proto_proto_rawDesc), len(file_chitchat_grpc_proto_proto_rawDesc)))
	})
	return file_chitchat_grpc_proto_proto_rawDescData
}

var file_chitchat_grpc_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chitchat_grpc_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chitchat_grpc_proto_proto_goTypes = []any{
	(BroadcastType)(0),    // 0: chitchat.v1.BroadcastType
	(*ClientMessage)(nil), // 1: chitchat.v1.ClientMessage
	(*ServerMessage)(nil), // 2: chitchat.v1.ServerMessage
	(*Join)(nil),          // 3: chitchat.v1.Join
	(*ChatMessage)(nil),   // 4: chitchat.v1.ChatMessage
	(*Leave)(nil),         // 5: chitchat.v1.Leave
	(*Broadcast)(nil),     // 6: chitchat.v1.Broadcast
	(*Error)(nil),         // 7: chitchat.v1.Error
	(*Ack)(nil),           // 8: chitchat.v1.Ack
}
var file_chitchat_grpc_proto_proto_depIdxs = []int32{
	3, // 0: chitchat.v1.ClientMessage.join:type_name -> chitchat.v1.Join
	4, // 1: chitchat.v1.ClientMessage.chat:type_name -> chitchat.v1.ChatMessage
	5, // 2: chitchat.v1.ClientMessage.leave:type_name -> chitchat.v1.Leave
	6, // 3: chitchat.v1.ServerMessage.broadcast:type_name -> chitchat.v1.Broadcast
	8, // 4: chitchat.v1.ServerMessage.ack:type_name -> chitchat.v1.Ack
	7, // 5: chitchat.v1.ServerMessage.error:type_name -> chitchat.v1.Error
	0, // 6: chitchat.v1.Broadcast.type:type_name -> chitchat.v1.BroadcastType
	1, // 7: chitchat.v1.ChitChat.Chat:input_type -> chitchat.v1.ClientMessage
	2, // 8: chitchat.v1.ChitChat.Chat:output_type -> chitchat.v1.ServerMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_chitchat_grpc_proto_proto_init() }
func file_chitchat_grpc_proto_proto_init() {
	if File_chitchat_grpc_proto_proto != nil {
		return
	}
	file_chitchat_grpc_proto_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Join)(nil),
		(*ClientMessage_Chat)(nil),
		(*ClientMessage_Leave)(nil),
	}
	file_chitchat_grpc_proto_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Broadcast)(nil),
		(*ServerMessage_Ack)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chitchat_grpc_proto_proto_rawDesc), len(file_chitchat_grpc_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chitchat_grpc_proto_proto_goTypes,
		DependencyIndexes: file_chitchat_grpc_proto_proto_depIdxs,
		EnumInfos:         file_chitchat_grpc_proto_proto_enumTypes,
		MessageInfos:      file_chitchat_grpc_proto_proto_msgTypes,
	}.Build()
	File_chitchat_grpc_proto_proto = out.File
	file_chitchat_grpc_proto_proto_goTypes = nil
	file_chitchat_grpc_proto_proto_depIdxs = nil
}
